version: '3'

services:
  scrapper:
    container_name: jncscrapper
    image : jncscrapper
    build : .
    volumes:
      - $PWD:/home/shared/
    networks:
      - jncscrapperbot

networks:
  jncscrapperbot:
